version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/todo
  - source: /todo.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStart:
    - location: start_service
      timeout: 300
      runas: root
